# Generated by Django 4.0.6 on 2022-07-21 07:43

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('72ae4735-10a6-4e4c-ac31-481924e939f6'), primary_key=True, serialize=False)),
                ('uploaded_at', models.DateField(auto_now=True)),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator('mp4')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
