# Generated by Django 4.0.6 on 2022-07-21 07:50

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('54ff0fa6-1737-4f15-984b-8f28b0ba2b03'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator('mp4', 'mpv')]),
        ),
    ]
