# Generated by Django 4.0.6 on 2022-07-21 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('61ee2a6b-5e80-4a1a-81bc-6d0df7edbbfc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
