# Generated by Django 4.0.6 on 2022-07-21 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('22a9d363-8fcb-47f0-8200-d0dfa1a41c7b'), primary_key=True, serialize=False),
        ),
    ]
