# Generated by Django 4.0.6 on 2022-07-21 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b8aa09b4-f9fb-46eb-889e-f4148b3f3da4'), primary_key=True, serialize=False),
        ),
    ]
