# Generated by Django 4.0.6 on 2022-07-21 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0496aa36-2149-4a96-9edc-38799f0c1c4a'), primary_key=True, serialize=False),
        ),
    ]
