# Generated by Django 4.0.6 on 2022-07-21 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4a46631e-9475-49f2-aa84-f7954f8cfdd5'), primary_key=True, serialize=False),
        ),
    ]
