# Generated by Django 4.0.6 on 2022-07-21 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('66680094-d92b-4c70-91ee-ad5e1a2df9f9'), primary_key=True, serialize=False),
        ),
    ]
