# Generated by Django 4.0.6 on 2022-07-21 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7de5fb75-91cb-489b-86c8-3684d74184b5'), primary_key=True, serialize=False),
        ),
    ]
