# Generated by Django 4.0.6 on 2022-07-21 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d357fbf6-9d58-40f2-abf0-e6e5d73ab598'), primary_key=True, serialize=False),
        ),
    ]
