# Generated by Django 4.0.6 on 2022-07-21 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('40ef9cf1-5ead-48ed-bab7-0008e76d461e'), primary_key=True, serialize=False),
        ),
    ]
