# Generated by Django 4.0.6 on 2022-07-21 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9e22f838-b973-4328-98e5-9d7741dd47b2'), primary_key=True, serialize=False),
        ),
    ]
