# Generated by Django 4.0.6 on 2022-07-21 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_alter_gallery_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3bfa3289-8c65-4827-aad5-62a49e68019f'), primary_key=True, serialize=False),
        ),
    ]
